### ISSUE TITLE
QT5 related installs are probably unnecessary now that we have them installed via vcpkg.json

### ISSUE THREAD

**Issue by tmargary** [tmargary/QuickTurns#26]
https://github.com/tmargary/QuickTurns/blob/b1c014cdcccc95b7d4103d947b8a854e5bd90e59/.github/workflows/main.yml#L42

**Comment by Mher594** [comment]
> https://github.com/tmargary/QuickTurns/blob/b1c014cdcccc95b7d4103d947b8a854e5bd90e59/.github/workflows/main.yml#L42

After moving Qt5 installation to vcpkg, build job probably should look like this: https://github.com/Mher594/ACA_calculator/blob/main/.github/workflows/build.yml
